// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZnySbbdN7gPdjOZqVSa3SG2cjn5wtHCU',
    appId: '1:919770299150:web:f683e75e51bc3bb2a7f55f',
    messagingSenderId: '919770299150',
    projectId: 'law-advisor-customer',
    authDomain: 'law-advisor-customer.firebaseapp.com',
    storageBucket: 'law-advisor-customer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADDYzy5_YNb3I3m0BJeKT-BN8SZM8kAWM',
    appId: '1:919770299150:android:b4839a6f6727e10ca7f55f',
    messagingSenderId: '919770299150',
    projectId: 'law-advisor-customer',
    storageBucket: 'law-advisor-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVkZ9IkevZkFe7wQgU7HNKnVrW8NBavIk',
    appId: '1:919770299150:ios:1622855c45df9126a7f55f',
    messagingSenderId: '919770299150',
    projectId: 'law-advisor-customer',
    storageBucket: 'law-advisor-customer.appspot.com',
    iosBundleId: 'com.lawadvisor.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVkZ9IkevZkFe7wQgU7HNKnVrW8NBavIk',
    appId: '1:919770299150:ios:1d4393dc517199cba7f55f',
    messagingSenderId: '919770299150',
    projectId: 'law-advisor-customer',
    storageBucket: 'law-advisor-customer.appspot.com',
    iosBundleId: 'com.example.customer',
  );
}
