<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GeneralSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('general_settings')->delete();

        \DB::table('general_settings')->insert(array (
            0 =>
            array (
                'created_at' => '2023-01-21 19:02:32',
                'display_name' => 'Facebook',
                'id' => 4,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'web_facebook_link',
                'page' => 'website_social_links',
                'type' => 'text',
                'updated_at' => '2023-01-18 13:38:43',
                'value' => 'https://facebook.com',
            ),
            1 =>
            array (
                'created_at' => '2023-01-21 18:28:25',
                'display_name' => 'Twitter',
                'id' => 5,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'web_twitter_link',
                'page' => 'website_social_links',
                'type' => 'text',
                'updated_at' => '2023-01-21 17:28:25',
                'value' => NULL,
            ),
            2 =>
            array (
                'created_at' => '2023-10-12 22:01:23',
                'display_name' => 'Logo',
                'id' => 6,
                'is_multilang' => 0,
                'is_specific' => 0,
                'name' => 'logo',
                'page' => NULL,
                'type' => 'image',
                'updated_at' => '2023-10-12 22:01:23',
                'value' => '/images/settings/logo.png',
            ),
            3 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 1 Heading',
                'id' => 11,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section1_heading',
                'page' => 'home_page_statistics',
                'type' => 'text',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => 'Members',
            ),
            4 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 1 Icon',
                'id' => 12,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section1_icon',
                'page' => 'home_page_statistics',
                'type' => 'text',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => 'bi bi-person-vcard-fill',
            ),
            5 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 1 Value',
                'id' => 13,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section1_value',
                'page' => 'home_page_statistics',
                'type' => 'number',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => '100',
            ),
            6 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 2 Heading',
                'id' => 17,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section2_heading',
                'page' => 'home_page_statistics',
                'type' => 'text',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => 'Lawyers',
            ),
            7 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 2 Icon',
                'id' => 18,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section2_icon',
                'page' => 'home_page_statistics',
                'type' => 'text',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => 'bi bi-person-heart',
            ),
            8 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 2 Value',
                'id' => 19,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section2_value',
                'page' => 'home_page_statistics',
                'type' => 'number',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => '77',
            ),
            9 =>
            array (
                'created_at' => '2023-08-25 21:36:16',
                'display_name' => 'Section 3 Heading',
                'id' => 24,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section3_heading',
                'page' => 'home_page_statistics',
                'type' => 'text',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => 'Appointments Booked',
            ),
            10 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 3 Icon',
                'id' => 25,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section3_icon',
                'page' => 'home_page_statistics',
                'type' => 'text',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => 'bi bi-calendar-heart-fill',
            ),
            11 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 3 Value',
                'id' => 26,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section3_value',
                'page' => 'home_page_statistics',
                'type' => 'number',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => '97',
            ),
            12 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 4 Heading',
                'id' => 27,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section4_heading',
                'page' => 'home_page_statistics',
                'type' => 'text',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => 'LawFirms',
            ),
            13 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 4 Icon',
                'id' => 28,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section4_icon',
                'page' => 'home_page_statistics',
                'type' => 'text',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => 'bi bi-buildings-fill',
            ),
            14 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 4 Value',
                'id' => 29,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section4_value',
                'page' => 'home_page_statistics',
                'type' => 'number',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => '84',
            ),
            15 =>
            array (
                'created_at' => '2023-01-21 19:02:19',
                'display_name' => 'Youtube',
                'id' => 30,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'web_youtube_link',
                'page' => 'website_social_links',
                'type' => 'text',
                'updated_at' => '2023-01-18 13:38:43',
                'value' => 'https://youtube.com',
            ),
            16 =>
            array (
                'created_at' => '2023-01-21 18:28:25',
                'display_name' => 'Linkedin',
                'id' => 31,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'web_linkedin_link',
                'page' => 'website_social_links',
                'type' => 'text',
                'updated_at' => '2023-01-21 17:28:25',
                'value' => 'https://linkedin.com',
            ),
            17 =>
            array (
                'created_at' => '2023-01-21 18:28:25',
                'display_name' => 'Whatsapp',
                'id' => 32,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'web_whatsapp_link',
                'page' => 'website_social_links',
                'type' => 'text',
                'updated_at' => '2023-01-21 17:28:25',
                'value' => 'https://whatsapp.com/asd',
            ),
            18 =>
            array (
                'created_at' => '2023-01-18 23:17:32',
                'display_name' => 'Footer Crisis Support Statement',
                'id' => 33,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'footer_crisis_support_statement',
                'page' => 'website_footer',
                'type' => 'textarea',
                'updated_at' => '2023-01-18 18:16:43',
                'value' => '<b>Don\'t use this site if:</b> You are in a crisis or if any other person may be in danger.',
            ),
            19 =>
            array (
                'created_at' => '2023-01-21 19:06:10',
                'display_name' => 'Instagram',
                'id' => 34,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'web_instagram_link',
                'page' => 'website_social_links',
                'type' => 'text',
                'updated_at' => '2023-01-21 17:28:25',
                'value' => 'https://instagram.com',
            ),
            20 =>
            array (
                'created_at' => '2023-01-21 19:02:19',
                'display_name' => 'Snapchat',
                'id' => 35,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'web_snapchat_link',
                'page' => 'website_social_links',
                'type' => 'text',
                'updated_at' => '2023-01-18 13:38:43',
                'value' => 'https://snapchat.com',
            ),
            21 =>
            array (
                'created_at' => '2023-01-21 18:28:25',
                'display_name' => 'Pinterest',
                'id' => 36,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'web_pinterest_link',
                'page' => 'website_social_links',
                'type' => 'text',
                'updated_at' => '2023-01-21 17:28:25',
                'value' => 'https://pinterest.com',
            ),
            22 =>
            array (
                'created_at' => '2023-01-21 18:28:25',
                'display_name' => 'TikTok',
                'id' => 37,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'web_tiktok_link',
                'page' => 'website_social_links',
                'type' => 'text',
                'updated_at' => '2023-01-21 17:28:25',
                'value' => 'https://tiktok.com',
            ),
            23 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 5 Heading',
                'id' => 38,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section5_heading',
                'page' => 'home_page_statistics',
                'type' => 'text',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => 'Events',
            ),
            24 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 5 Icon',
                'id' => 39,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section5_icon',
                'page' => 'home_page_statistics',
                'type' => 'text',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => 'bi bi-balloon-heart-fill',
            ),
            25 =>
            array (
                'created_at' => '2023-02-15 22:08:43',
                'display_name' => 'Section 5 Value',
                'id' => 40,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'home_section5_value',
                'page' => 'home_page_statistics',
                'type' => 'number',
                'updated_at' => '2023-02-15 21:08:43',
                'value' => '100',
            ),
            26 =>
            array (
                'created_at' => '2023-02-16 02:08:43',
                'display_name' => 'AGORA APP ID',
                'id' => 41,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'agora_app_id',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2023-02-16 01:08:43',
                'value' => 'ee3d69d271fb409e93347069503f4803',
            ),
            27 =>
            array (
                'created_at' => '2023-02-16 02:08:43',
                'display_name' => 'AGORA APP CERTIFICATE',
                'id' => 43,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'agora_app_certificate',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2023-02-16 01:08:43',
                'value' => '3f8f4c99dc2748db88a286fbbfc6b1c7',
            ),
            28 =>
            array (
                'created_at' => '2023-02-16 02:08:43',
                'display_name' => 'PUSHER BEAMS INSTANCE ID',
                'id' => 44,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'pusher_beams_instance_id',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2023-02-16 01:08:43',
                'value' => '41feeeff-28a1-4aca-8e1f-367d292906ec',
            ),
            29 =>
            array (
                'created_at' => '2023-02-16 02:08:43',
                'display_name' => 'PUSHER BEAMS SECRET KEY',
                'id' => 45,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'pusher_beams_secret_key',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2023-02-16 01:08:43',
                'value' => '0F3C4B8299756A807C1A9D293B5E18CAEE0D5EBB0F258E091AED8BBBAF8D64DF',
            ),
            30 =>
            array (
                'created_at' => '2023-02-16 02:08:43',
                'display_name' => 'PUSHER APP ID',
                'id' => 46,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'pusher_app_id',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2023-02-16 01:08:43',
                'value' => '1665700',
            ),
            31 =>
            array (
                'created_at' => '2023-02-16 02:08:43',
                'display_name' => 'PUSHER APP KEY',
                'id' => 47,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'pusher_app_key',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2023-02-16 01:08:43',
                'value' => '9d8e7b5c8ce69b2c07af',
            ),
            32 =>
            array (
                'created_at' => '2023-02-16 02:08:43',
                'display_name' => 'PUSHER APP SECRET',
                'id' => 48,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'pusher_app_secret',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2023-02-16 01:08:43',
                'value' => '3249dca6b5e76fc1a98d',
            ),
            33 =>
            array (
                'created_at' => '2023-02-16 02:08:43',
                'display_name' => 'PUSHER APP CLUSTER',
                'id' => 49,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'pusher_app_cluster',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2023-02-16 01:08:43',
                'value' => 'ap2',
            ),
            34 =>
            array (
                'created_at' => '2023-11-01 17:18:22',
                'display_name' => 'STRIPE KEY',
                'id' => 50,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'stripe_key',
                'page' => 'payment_method_settings',
                'type' => 'text',
                'updated_at' => '2023-11-01 17:18:22',
                'value' => 'pk_test_51MjnELHTAHWwyrB6HqKFzapBSOjSEAF9dKUz7JAI9vPTQHtsGsFJrhm151hdiVQWyvsvtq1CpkSMEmAUjC0pgbEl00P1BNfXvD',
            ),
            35 =>
            array (
                'created_at' => '2023-11-01 17:18:22',
                'display_name' => 'STRIPE SECRET',
                'id' => 51,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'stripe_secret',
                'page' => 'payment_method_settings',
                'type' => 'text',
                'updated_at' => '2023-11-01 17:18:22',
                'value' => 'sk_test_51MjnELHTAHWwyrB6o5FbJewlU1QQeOvwfJoCBfnlf20KzNGa7JVyxIWhYIb84Ohl8kUxvGDuzOkCSo3rFj9Ne85l00FvdXN2ti',
            ),
            36 =>
            array (
                'created_at' => '2023-02-16 02:08:43',
                'display_name' => 'GOOGLE CLIENT ID',
                'id' => 52,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'google_client_id',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2023-02-16 01:08:43',
                'value' => '1006558285844-81r1j9n23vovqg9uebrae8tcg79v7t4b.apps.googleusercontent.com',
            ),
            37 =>
            array (
                'created_at' => '2023-02-16 02:08:43',
                'display_name' => 'GOOGLE CLIENT SECRET',
                'id' => 53,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'google_client_secret',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2023-02-16 01:08:43',
                'value' => 'Uru8dkoJjf3ey401DG8gLaq5',
            ),
            38 =>
            array (
                'created_at' => '2023-02-16 02:08:43',
                'display_name' => 'FACEBOOK CLIENT ID',
                'id' => 54,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'facebook_client_id',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2023-02-16 01:08:43',
                'value' => '887082349379468',
            ),
            39 =>
            array (
                'created_at' => '2023-02-16 02:08:43',
                'display_name' => 'FACEBOOK CLIENT SECRET',
                'id' => 55,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'facebook_client_secret',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2023-02-16 01:08:43',
                'value' => '163a1cc69bd8a9706700e816544b1429',
            ),
            40 =>
            array (
                'created_at' => '2024-05-14 12:57:49',
                'display_name' => 'Contact Us Receiving Email',
                'id' => 56,
                'is_multilang' => 0,
                'is_specific' => 0,
                'name' => 'contact_us_email',
                'page' => NULL,
                'type' => 'email',
                'updated_at' => '2024-05-14 12:57:49',
                'value' => 'info@hexathemes.com',
            ),
            41 =>
            array (
                'created_at' => '2024-05-14 12:57:49',
                'display_name' => 'Site Title',
                'id' => 57,
                'is_multilang' => 0,
                'is_specific' => 0,
                'name' => 'site_title',
                'page' => NULL,
                'type' => 'text',
                'updated_at' => '2024-05-14 12:57:49',
                'value' => 'LawAdvisor',
            ),
            42 =>
            array (
                'created_at' => '2024-05-14 12:57:49',
                'display_name' => 'Enable Wallet System',
                'id' => 59,
                'is_multilang' => 0,
                'is_specific' => 0,
                'name' => 'enable_wallet_system',
                'page' => NULL,
                'type' => 'boolean_selection',
                'updated_at' => '2024-05-14 12:57:49',
                'value' => '1',
            ),
            43 =>
            array (
                'created_at' => '2024-05-14 12:57:49',
                'display_name' => 'Select Commission Type',
                'id' => 60,
                'is_multilang' => 0,
                'is_specific' => 0,
                'name' => 'commission_type',
                'page' => NULL,
                'type' => 'select_option',
                'updated_at' => '2024-05-14 12:57:49',
                'value' => 'commission_base',
            ),
            44 =>
            array (
                'created_at' => '2024-06-13 14:04:14',
                'display_name' => 'Application Current Version',
                'id' => 61,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'application_current_version',
                'page' => NULL,
                'type' => 'text',
                'updated_at' => '2024-05-14 16:59:45',
                'value' => '1.0.5',
            ),
            45 =>
            array (
                'created_at' => '2024-05-21 17:51:09',
                'display_name' => 'Mail Driver',
                'id' => 62,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'mail_driver',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2024-05-14 16:59:45',
                'value' => 'smtp',
            ),
            46 =>
            array (
                'created_at' => '2024-05-21 17:51:09',
                'display_name' => 'Mail Host',
                'id' => 63,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'mail_host',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2024-05-14 16:59:45',
                'value' => 'sandbox.smtp.mailtrap.io',
            ),
            47 =>
            array (
                'created_at' => '2024-05-21 17:51:09',
                'display_name' => 'Mail Port',
                'id' => 64,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'mail_port',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2024-05-14 16:59:45',
                'value' => '587',
            ),
            48 =>
            array (
                'created_at' => '2024-05-21 17:51:09',
                'display_name' => 'Mail Username',
                'id' => 65,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'mail_username',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2024-05-14 16:59:45',
                'value' => '5e61912602edf9',
            ),
            49 =>
            array (
                'created_at' => '2024-05-21 17:49:28',
                'display_name' => 'Mail Password',
                'id' => 66,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'mail_password',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2024-05-14 16:59:45',
                'value' => '275f0deee12cf5',
            ),
            50 =>
            array (
                'created_at' => '2024-05-21 17:49:28',
                'display_name' => 'Mail Encryption',
                'id' => 67,
                'is_multilang' => 0,
                'is_specific' => 1,
                'name' => 'mail_encryption',
                'page' => 'configurations',
                'type' => 'text',
                'updated_at' => '2024-05-14 16:59:45',
                'value' => 'null',
            ),
            51 =>
            array (
                'created_at' => '2024-06-14 12:39:46',
                'display_name' => 'Auto Approve Lawyer Service',
                'id' => 68,
                'is_multilang' => 0,
                'is_specific' => 0,
                'name' => 'auto_approve_lawyer_service',
                'page' => '',
                'type' => 'boolean_selection',
                'updated_at' => '2023-02-16 02:08:43',
                'value' => '1',
            ),
            52 =>
            array (
                'created_at' => '2024-05-14 17:49:16',
                'display_name' => 'Auto Approve Law Firm Service',
                'id' => 69,
                'is_multilang' => 0,
                'is_specific' => 0,
                'name' => 'auto_approve_law_firm_service',
                'page' => '',
                'type' => 'boolean_selection',
                'updated_at' => '2023-02-16 02:08:43',
                'value' => '1',
            ),
            53 =>
            array (
                'created_at' => '2024-05-14 17:49:16',
                'display_name' => 'Show Community Form',
                'id' => 70,
                'is_multilang' => 0,
                'is_specific' => 0,
                'name' => 'is_community_form_show',
                'page' => '',
                'type' => 'boolean_selection',
                'updated_at' => '2023-02-16 02:08:43',
                'value' => '1',
            ),
            54 =>
            array (
                'created_at' => '2024-09-05 10:15:08',
                'display_name' => 'Is AI chatBot Enable',
                'id' => 71,
                'is_multilang' => 0,
                'is_specific' => 0,
                'name' => 'is_ai_chatbot_enable',
                'page' => '',
                'type' => 'boolean_selection',
                'updated_at' => '2023-02-16 02:08:43',
                'value' => '1',
            ),
            55 =>
            array (
                'created_at' => '2024-12-12 16:00:00',
                'display_name' => 'Auto Approve Users',
                'id' => 72,
                'is_multilang' => 0,
                'is_specific' => 0,
                'name' => 'is_auto_approve',
                'page' => '',
                'type' => 'boolean_selection',
                'updated_at' => '2024-12-12 16:00:00',
                'value' => '1',
            ),
        ));


    }
}
